-- Fix RLS: ensure every table has a permissive policy so the anon key works.
-- Safe to run multiple times. Run this in the Supabase SQL Editor.

alter table products enable row level security;
drop policy if exists "Allow all" on products;
create policy "Allow all" on products for all using (true) with check (true);
alter table farms enable row level security;
drop policy if exists "Allow all" on farms;
create policy "Allow all" on farms for all using (true) with check (true);
alter table dispatches enable row level security;
drop policy if exists "Allow all" on dispatches;
create policy "Allow all" on dispatches for all using (true) with check (true);
alter table dispatch_items enable row level security;
drop policy if exists "Allow all" on dispatch_items;
create policy "Allow all" on dispatch_items for all using (true) with check (true);
alter table payments enable row level security;
drop policy if exists "Allow all" on payments;
create policy "Allow all" on payments for all using (true) with check (true);
alter table expenses enable row level security;
drop policy if exists "Allow all" on expenses;
create policy "Allow all" on expenses for all using (true) with check (true);
alter table stock_purchases enable row level security;
drop policy if exists "Allow all" on stock_purchases;
create policy "Allow all" on stock_purchases for all using (true) with check (true);
alter table customers enable row level security;
drop policy if exists "Allow all" on customers;
create policy "Allow all" on customers for all using (true) with check (true);
alter table sales enable row level security;
drop policy if exists "Allow all" on sales;
create policy "Allow all" on sales for all using (true) with check (true);
alter table sale_items enable row level security;
drop policy if exists "Allow all" on sale_items;
create policy "Allow all" on sale_items for all using (true) with check (true);
alter table supply_payments enable row level security;
drop policy if exists "Allow all" on supply_payments;
create policy "Allow all" on supply_payments for all using (true) with check (true);
alter table suppliers enable row level security;
drop policy if exists "Allow all" on suppliers;
create policy "Allow all" on suppliers for all using (true) with check (true);
alter table supplier_dispatches enable row level security;
drop policy if exists "Allow all" on supplier_dispatches;
create policy "Allow all" on supplier_dispatches for all using (true) with check (true);
alter table supplier_payments enable row level security;
drop policy if exists "Allow all" on supplier_payments;
create policy "Allow all" on supplier_payments for all using (true) with check (true);
alter table settings enable row level security;
drop policy if exists "Allow all" on settings;
create policy "Allow all" on settings for all using (true) with check (true);
alter table cash_ledger enable row level security;
drop policy if exists "Allow all" on cash_ledger;
create policy "Allow all" on cash_ledger for all using (true) with check (true);
alter table market_sellers enable row level security;
drop policy if exists "Allow all" on market_sellers;
create policy "Allow all" on market_sellers for all using (true) with check (true);
alter table market_transactions enable row level security;
drop policy if exists "Allow all" on market_transactions;
create policy "Allow all" on market_transactions for all using (true) with check (true);
alter table chicken_deaths enable row level security;
drop policy if exists "Allow all" on chicken_deaths;
create policy "Allow all" on chicken_deaths for all using (true) with check (true);
alter table choza_transactions enable row level security;
drop policy if exists "Allow all" on choza_transactions;
create policy "Allow all" on choza_transactions for all using (true) with check (true);
alter table commission_cars enable row level security;
drop policy if exists "Allow all" on commission_cars;
create policy "Allow all" on commission_cars for all using (true) with check (true);
alter table commission_customers enable row level security;
drop policy if exists "Allow all" on commission_customers;
create policy "Allow all" on commission_customers for all using (true) with check (true);
alter table commission_sales enable row level security;
drop policy if exists "Allow all" on commission_sales;
create policy "Allow all" on commission_sales for all using (true) with check (true);
alter table commission_payments enable row level security;
drop policy if exists "Allow all" on commission_payments;
create policy "Allow all" on commission_payments for all using (true) with check (true);
alter table commission_car_expenses enable row level security;
drop policy if exists "Allow all" on commission_car_expenses;
create policy "Allow all" on commission_car_expenses for all using (true) with check (true);
alter table commission_dealers enable row level security;
drop policy if exists "Allow all" on commission_dealers;
create policy "Allow all" on commission_dealers for all using (true) with check (true);
alter table commission_dealer_payments enable row level security;
drop policy if exists "Allow all" on commission_dealer_payments;
create policy "Allow all" on commission_dealer_payments for all using (true) with check (true);
alter table commission_fee_expenses enable row level security;
drop policy if exists "Allow all" on commission_fee_expenses;
create policy "Allow all" on commission_fee_expenses for all using (true) with check (true);
alter table app_users enable row level security;
drop policy if exists "Allow all" on app_users;
create policy "Allow all" on app_users for all using (true) with check (true);
